### ISSUE TITLE
ex07 adv pastel oracle query code

### ISSUE THREAD

**Issue by GiovanniMontero** [GiovanniMontero/GM-RD#2]
Here's my code for the first query where we look for all occurrences of adv pastel in the courses table take a look: 

// 3. Write and run an SQL query to list all occurrences of Adv Pastels in the COURSE table. 
Include all associated data for each occurrence of the class.//
SELECT * FROM COURSE
WHERE COURSE = Adv Pastels;

**Comment by RyanDuerkes** [comment]
that works
