### ISSUE TITLE
ORACLE Query #2 finding students and courses

### ISSUE THREAD

**Issue by GiovanniMontero** [GiovanniMontero/GM-RD#3]
Heres the queries i wrote to find the students and the courses they're enrolled in using join and on statements take a look:

SELECT C.CustomerNumber, C.CustomerLastName, C.CustomerFirstname, C.Phone, E.CourseNumber, E.AmountPaid
FROM CUSTOMER C

JOIN ENROLLMENT E
ON C.CUSTOMERNUMBER = E.CUSTOMERNUMBER;

**Comment by RyanDuerkes** [comment]
it works
