### ISSUE TITLE
Oracle query 3 finding students who enrolled in Adv. Pastels on Oct. 1 2019

### ISSUE THREAD

**Issue by GiovanniMontero** [GiovanniMontero/GM-RD#4]
Here's the code I used to find students who enrolled in Adv Pastels on October 1st 2019 take a look:

SELECT C.Course, C.CourseDate, C.Fee, CR.CustomerLastName, CR.CustomerFirstname, CR.Phone
FROM CUSTOMER CR
JOIN ENROLLMENT E
ON CR.CustomerNumber=E.CustomerNumber
JOIN COURSE C
ON C.COURSENUMBER=E.COURSENUMBER
WHERE CourseDate = To_Date('10/01/2019', 'mm/dd/yyyy')

AND C.Course = 'Adv Pastels';

**Comment by RyanDuerkes** [comment]
it works
