### ISSUE TITLE
Oracle Query #4 All Students Registered In Adv. Pastels Starting On October 1, 2017

### ISSUE THREAD

**Issue by RyanDuerkes** [GiovanniMontero/GM-RD#5]
SELECT C.Course, C.CourseDate, CR.CustomerLastName, CR.CustomerFirstName, CR.Phone, C.Fee, E.AmountPaid
From Customer CR
Join Enrollment E
on CR.CustomerNumber = E.CustomerNumber
JOIN COURSE C
ON C.COURSENUMBER = E.COURSENUMBER
WHERE CourseDate = To_Date('10/01/2019', 'mm/dd/yyyy')

AND C.Course = 'Adv Pastels';

**Comment by GiovanniMontero** [comment]
Looks good!
